const flashcards = [
    { que: "2.1.1: Application Logging",
        ans: `Event Logs: record events as they occur.
        Transaction Logs: frequently used with databases to track data changes.
        Message Logs: track public/private chat messages.
        Server Logs: track non-user-specific activities by server.` },
    { que: "Preventing, Responding to Incidents p834-845",
        ans: `` },
    { que: "Security Logs",
        ans: `records access to resources(files, folders, printers)` },
    { que: "System Logs",
        ans: `record system events(when system starts/stops, services start/stop, when service attributes are modded).
        Attackers can shutdown/start system with USB drive and steal data without record of data access.
        Attackers can stop services that monitor the system and access the system without logs recording their actions.
        Attackers can modify attributes of logs.
        Ex: service might be set to Disabled, but attacker can change it to Manual` },
    { que: "Application Logs",
        ans: `Record info for specific applications. Ex: database devs choose to record when someone accesses specific data objects such as tables/views.` },
    { que: "Firewall Logs",
        ans: `Record events related to traffic reaching the firewall, including traffic that firewall allows/blocks. They log packet info (source and destination IP address)` },
    { que: "Proxy Logs",
        ans: `proxy servers improve internet access performance for users and control websites users can visit. Proxy logs have ability to record what sites users visit and how much time they spend on the sites. Can record when users attempt to visit prohibited sites.` },
    { que: "Change Logs",
        ans: `record change requests, approvals, actual changes.
        Can help with disaster recovery, ex: administrators and technicians use change logs to return a system to last known state after a disaster.` },
    { que: "Protecting Log Data",
        ans: `Personnel in the company can use logs to re-create events leading up to and during an incident, but only if logs haven't been modified. If attackers modify the logs, they can erase their activity, nullifying the value of the data. The file information is no longer accurate.
        Protect log files against unauthorized access/modifications.
        Common to store copies of logs on central system, such as security information and event management(SIEM) system for protection.
        National Institue of Standards and Technology(NIST) publishes info on IT security, including Federal Information Processing Standards(FIPS) publications.` },
    { que: "Role of Monitoring",
        ans: `increases accountability, helps investigations, basic troubleshooting.` },
    { que: "Audit Trails",
        ans: `Records information about events and stored in databases or log files.
        Security professionals extract info from audit trail to dis/prove culpability. Can examine and trace events forward/reverse order.
        The flexibility helps tracking down problems, performance issues, attacks, intrusions, security breaches, coding errors, other policy violations.` },
    { que: "Monitoring and Accountability",
        ans: `Monitoring ensure subjects(users/employees) are held accountable for their actions.
        Users claim identity(with username) and prove identity(authentication), and audit trails record their activity while logged in.` },
    { que: "Monitoring and Investigations.",
        ans: `Make sure logs have accurate timestamps. Common method is internal Network Time Protocol(NTP) server synced to trusted time source (public NTP server).` },
    { que: "Monitoring and Problem Identification",
        ans: `Audit trails offer details about recorded events, useful for administrators. They record system failures, OS bugs, software errors, malicious attacks. Log files can capture memory contents when app/system crashes. This helps pinpoint cause of event; ex: if system crashes due to faulty memory, crash dump files diagnose the problem.` },
    { que: "Monitoring Techniques",
        ans: `Monitoring: process of reviewing logs for something specific.Log analysis: detailed and systematic form of monitoring which the logged information is analyzed.` },
    { que: "Security Information and Event Management(SIEM)",
        ans: `"security event management(SEM)", "security information management(SIM)": are tools that provide centaralized logging and real-time analysis of events occurring on systems throughtout an organization. They include agents installed on remote systems that monitor alarm triggers.` },
    { que: "Syslog",
        ans: `RFC 5424, Syslog Protocol, sends event notifications. Centralized syslog server receives syslog messages from devices on a network.` },
    { que: "Sampling",
        ans: `"data extraction": the process of extracting specifics from a large collection of data to construct meaningful representation or summary of a whole. Sampling is a form of data reduction to glean valuable information.` },
    { que: "Clipping Levels",
        ans: `form of nonstatistical sampling. Selects events that exceed "clipping level", a predefined threshold for the event.
        Ex: failed logon attempts are common. Instead of alarming every failed logon, clipping level can be set to raise alarm on five logon attempts within 30-minute period.
        Monitoring system alarms when baseline is exceeded.` },
    { que: "Other Monitoring Tools",
        ans: `ex: CCTV record events on tape for later review.` },
    { que: "Keystroke Monitoring",
        ans: `records keystrokes a user performs on a physical keyboard. Records using hardware or software know as "keylogger".
        Video recorder perform visual monitoring.
        Attackers use keystroke monitoring for malicious purposes
        Keystroke monitoring is compared to wiretapping..` },
    { que: "Traffic and Trend Analysis",
        ans: `form of monitoring that examine flow of packets than packet contents. These processes are aka "network flow monitoring".` },
    { que: "Log Management",
        ans: `refers to all methods used to collect, process, protect log entries.
        SIEM collects and aggregates log entries, then analyzes entries and report suspicious events. After systems forwards log entries to SIEM, it deletes the log entries. But they're not deleted right away, instead use "rollover logging" aka "circular logging" or "log cycling". It begins overwriting old events. ` },
    { que: "Egress Monitoring",
        ans: `traffic leaving a network to the internet. Can detect unauthorized transfer of data outside organization aka "data exfiltration". Methods to detect/prevent data exfil are data loss prevention (DLP) techniques and monitoring for steganography.` },
    { que: "Steganography",
        ans: `allows attackers to embed messages within files (graphic/audio files). Possible to detect steganography attempts if you have both original file and fild you suspect has hidden message.` },
    { que: "Digital Watermark",
        ans: `secretly embedded marker in a digital file. Ex: movie studios digitally mark copies of moives sent to different distributors. Each copy has different mark, if any distributors released pirated copies, the studio can identify which.` },
    { que: "logging - Logging facility for Python",
        ans: `https://docs.python.org/3/library/logging.html` },
    { que: "Debugging",
        ans: `when code is not working right, a developer debugs their code by instrumenting, executing, and inspecting the code.` },
    { que: "Why is debugging important?",
        ans: `improve efficiency of an application by optimizing performance and improving logic.` },
    { que: "Debugging Techniques",
        ans: `Printing out or displaying values of variables and state at certain times during the execution of an application.
        Changing the state of a program to make it do different things. Aka altering the "path" of the program.
        Stepping through the execution of a program line by line.
        Breakpoints.
        Trace Points
        Stopping the program at certain events.
        Viewing the output of a program in a debugger window.` },
    { que: "Debugging Tools",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
];