const flashcards = [
    { que: "2.1.1: Application Logging",
        ans: `Event Logs: record events as they occur.
        Transaction Logs: frequently used with databases to track data changes.
        Message Logs: track public/private chat messages.
        Server Logs: track non-user-specific activities by server.` },
    { que: "Preventing, Responding to Incidents p834-845",
        ans: `` },
    { que: "Security Logs",
        ans: `records access to resources(files,folders,printers)` },
    { que: "System Logs",
        ans: `record system events(when system starts/stops, services start/stop, when service attributes are modded).
        Attackers can shutdown/start system with USB drive and steal data without record of data access.
        Attackers can stop services that monitor the system and access the system without logs recording their actions.
        Attackers can modify attributes of logs.
        Ex: service might be set to Disabled, but attacker can change it to Manual` },
    { que: "Application Logs",
        ans: `Record info for specific applications. Ex: database devs choose to record when someone accesses specific data objects such as tables/views.` },
    { que: "Firewall Logs",
        ans: `Record events related to traffic reaching the firewall, including traffic that firewall allows/blocks. They log packet info (source and destination IP address)` },
    { que: "Proxy Logs",
        ans: `proxy servers improve internet access performance for users and control websites users can visit. Proxy logs have ability to record what sites users visit and how much time they spend on the sites. Can record when users attempt to visit prohibited sites.` },
    { que: "Change Logs",
        ans: `record change requests, approvals, actual changes.
        Can help with disaster recovery, ex: administrators and technicians use change logs to return a system to last known state after a disaster.` },
    { que: "Protecting Log Data",
        ans: `Personnel in the company can use logs to re-create events leading up to and during an incident, but only if logs haven't been modified. If attackers modify the logs, they can erase their activity, nullifying the value of the data. The file information is no longer accurate.
        Protect log files against unauthorized access/modifications.
        Common to store copies of logs on central system, such as security information and event management(SIEM) system for protection.
        National Institue of Standards and Technology(NIST) publishes info on IT security, including Federal Information Processing Standards(FIPS) publications.` },
    { que: "Role of Monitoring",
        ans: `increases accountability, helps investigations, basic troubleshooting.` },
    { que: "Audit Trails",
        ans: `Records information about events and stored in databases or log files.
        Security professionals extract info from audit trail to dis/prove culpability. Can examine and trace events forward/reverse order.
        The flexibility helps tracking down problems, performance issues, attacks, intrusions, security breaches, coding errors, other policy violations.` },
    { que: "Monitoring and Accountability",
        ans: `Monitoring ensure subjects(users/employees) are held accountable for their actions.
        Users claim identity(with username) and prove identity(authentication), and audit trails record their activity while logged in.` },
    { que: "Monitoring and Investigations.",
        ans: `Make sure logs have accurate timestamps. Common method is internal Network Time Protocol(NTP) server synced to trusted time source (public NTP server).` },
    { que: "Monitoring and Problem Identification",
        ans: `Audit trails offer details about recorded events, useful for administrators. They record system failures, OS bugs, software errors, malicious attacks. Log files can capture memory contents when app/system crashes. This helps pinpoint cause of event; ex: if system crashes due to faulty memory, crash dump files diagnose the problem.` },
    { que: "Monitoring Techniques",
        ans: `Monitoring: process of reviewing logs for something specific.Log analysis: detailed and systematic form of monitoring which the logged information is analyzed.` },
    { que: "Security Information and Event Management(SIEM)",
        ans: `"security event management(SEM)", "security information management(SIM)": are tools that provide centaralized logging and real-time analysis of events occurring on systems throughtout an organization. They include agents installed on remote systems that monitor alarm triggers.` },
    { que: "Syslog",
        ans: `RFC 5424, Syslog Protocol, sends event notifications. Centralized syslog server receives syslog messages from devices on a network.` },
    { que: "Sampling",
        ans: `"data extraction": the process of extracting specifics from a large collection of data to construct meaningful representation or summary of a whole. Sampling is a form of data reduction to glean valuable information.` },
    { que: "Clipping Levels",
        ans: `form of nonstatistical sampling. Selects events that exceed "clipping level", a predefined threshold for the event.
        Ex: failed logon attempts are common. Instead of alarming every failed logon, clipping level can be set to raise alarm on five logon attempts within 30-minute period.
        Monitoring system alarms when baseline is exceeded.` },
    { que: "Other Monitoring Tools",
        ans: `ex: CCTV record events on tape for later review.` },
    { que: "Keystroke Monitoring",
        ans: `records keystrokes a user performs on a physical keyboard. Records using hardware or software know as "keylogger".
        Video recorder perform visual monitoring.
        Attackers use keystroke monitoring for malicious purposes
        Keystroke monitoring is compared to wiretapping..` },
    { que: "Traffic and Trend Analysis",
        ans: `form of monitoring that examine flow of packets than packet contents. These processes are aka "network flow monitoring".` },
    { que: "Log Management",
        ans: `refers to all methods used to collect, process, protect log entries.
        SIEM collects and aggregates log entries, then analyzes entries and report suspicious events. After systems forwards log entries to SIEM, it deletes the log entries. But they're not deleted right away, instead use "rollover logging" aka "circular logging" or "log cycling". It begins overwriting old events. ` },
    { que: "Egress Monitoring",
        ans: `traffic leaving a network to the internet. Can detect unauthorized transfer of data outside organization aka "data exfiltration". Methods to detect/prevent data exfil are data loss prevention (DLP) techniques and monitoring for steganography.` },
    { que: "Steganography",
        ans: `allows attackers to embed messages within files (graphic/audio files). Possible to detect steganography attempts if you have both original file and fild you suspect has hidden message.` },
    { que: "Digital Watermark",
        ans: `secretly embedded marker in a digital file. Ex: movie studios digitally mark copies of moives sent to different distributors. Each copy has different mark, if any distributors released pirated copies, the studio can identify which.` },
    { que: "📁 logging - Logging facility for Python",
        ans: `https://docs.python.org/3/library/logging.html` },
    { que: "Debugging",
        ans: `when code is not working right, a developer debugs their code by instrumenting, executing, and inspecting the code.` },
    { que: "Why is debugging important?",
        ans: `improve efficiency of an application by optimizing performance and improving logic.` },
    { que: "Debugging Techniques",
        ans: `Printing out or displaying values of variables and state at certain times during the execution of an application.
        Changing the state of a program to make it do different things. Aka altering the "path" of the program.
        Stepping through the execution of a program line by line.
        Breakpoints.
        Trace Points
        Stopping the program at certain events.
        Viewing the output of a program in a debugger window.` },
    { que: "Debugging Tools - pdb",
        ans: `most commonly-used debugger built into the Python standard library and is the one most developers come across first when trying to debug their programs.` },
    { que: "Debugging Tools - Web-PDB",
        ans: `provides a web-based user interface for pdb to make it easier to understand what is happening while inspecting your running code.` },
    { que: "Debugging Tools - wdb",
        ans: `uses WebSockets to allow you to debug running Python code from a web browser.` },
    { que: "Debugging Tools - Pyflame",
        ans: `a profiling tool that generates flame graphs for executing Python program code.` },
    { que: "Debugging Tools - objgraph",
        ans: `uses graphviz to draw the connections between Python objects running in an application` },
    { que: "📁 Debugging and Profiling - python docs",
        ans: `https://docs.python.org/3/library/debug.html` },
    { que: "📁 Hacking and Securing Python Applications web site",
        ans: `https://qwiet.ai/hacking-and-securing-python-applications/` },
    { que: "XML External Entity (XXE) Attack",
        ans: `when attackers exploit an XML parser to read arbitrary files on your server. Using an XXE, attackers might also be able to retrieve user information, configuration files, or other sensitive information like AWS credentials. To prevent XXE attacks, you need to explicitly disable these functionalities.` },
    { que: "Insecure Deserialization",
        ans: `Serialization: process which an object in programming language is converted into a format that can be saved to the database or transferred over a network. 
        Deserialization: the opposite: when serialized object is read from a file or the network and converted back into an object.
        Insecure deserialization: when attacker manipulate the serialized object and cause unintended consequences in the program’s flow. Insecure deserialization bug will often result in authentication bypass, denial of service, or arbitrary code execution.
        To prevent insecure deserialization, keep an eye out for patches and keep dependencies up to date. Helps to avoid using serialized objects and use sime simple data types(strings/arrays) instead.` },
    { que: "Remote Code Execution (RCE)",
        ans: `when attackers execute their code on your machine. This can happen through command injection vulnerabilities. They are a type of remote code execution that happens when user input is concatenated directly into system command. The application cannot distinguish between where user input is and where system command is, so the application executes user input as code. Attacker will be able to execute arbitrary commands on the machine.
        To prevent command injection is to implement robust input validation in the form of an allowlist. ` },
    { que: "SQL Injection",
        ans: `attacker injects data to manipulate SQL commands. When the application does not validate user input properly, attackers can insert characters special to the SQL language to mess with the query’s logic, thereby executing arbitrary SQL code.
        SQL injections allow attacker code to change the structure of application’s SQL queries to steal/modify data, or execute arbitrary commands in the underlying operating system. Best way to prevent SQL injections is to use parameterized statements, which makes SQL injection virtually impossible.` },
    { que: "NoSQL Injection",
        ans: `NoSQL(Not Only SQL) databases, don’t use SQL language. NoSQL injection refers to attacks that inject data into the logic of these database. These attacks can lead to authentication bypass and remote code execution.` },
    { que: "LDAP Injection",
        ans: `Lightweight Directory Access Protocol (LDAP): way of querying a directory service about the system’s users and devices. Ex: it’s used to query Microsoft’s Active Directory. When an application uses untrusted input in LDAP queries, attackers can submit crafted inputs that cause malicious effects. Using LDAP injection, attackers can bypass authentication and mess with the data in the directory. Use parameterized queries to prevent LDAP injection. ` },
    { que: "Log Injection",
        ans: `Attackers often modify log files to cover up their tracks during an attack. Log injection is one of the ways attackers can change your log files. It happens when the attacker tricks the application into writing fake entries in your log files.
        Log injection often happens when the application does not sanitize newline characters “\n” in input written to logs. Attackers can make use of the new line character to insert new entries into application logs. Another way attackers can exploit user input in logs is that they can inject malicious HTML into log entries to attempt to trigger an XSS on the browser of the admin who views the logs.
        To prevent log injection attacks, you need a way to distinguish between real log entries, and fake log entries injected by the attacker. One way to do this is by prefixing each log entry with extra meta-data like a timestamp, process ID, and hostname. You should also treat the contents of log files as untrusted input and validate it before accessing or operating on it.` },
    { que: "Mail Injection",
        ans: `web applications send emails to users based on their actions. For instance, if you subscribed to a feed on a news outlet, the website might send you a confirmation with the name of the feed.
        Mail injection happens when the application employs user input to determine which addresses to send emails to. This can allow spammers to use your server to send bulk emails to users or enable scammers to conduct social engineering campaigns via your email address. ` },
    { que: "Template Injection",
        ans: `Template engines are a type of software used to determine the appearance of a web page. These web templates, written in template languages such as Jinja, provide developers with a way to specify how a page should be rendered by combining application data with web templates. Together, web templates and template engines allow developers to separate server-side application logic from client-side presentation code during web development.
        Template injection refers to injection into web templates. Depending on the permissions of the compromised application, attackers might be able to use the template injection vulnerability to read sensitive files, execute code, or escalate their privileges on the system.` },
    { que: "Regex Injection",
        ans: `regular expression(regex) is a special string that describes a search pattern in text. ex: applications let users provide their own regex patterns for the server to execute or build a regex with user input. Regex injection or regular expression denial of service attack (ReDoS), happens when an attacker provides a regex engine with a pattern that takes a long time to evaluate.
        Regex injection can be prevented by not generating regex patterns from user input, and by constructing well-designed regex patterns whose required computing time does not grow exponentially as the text string grows. ` },
    { que: "XPath Injection",
        ans: `a query language for XML documents(SQL for XML). XPath is used to query and perform operations on data stored in XML documents. For example, XPath can be used to retrieve salary information of employees stored in an XML document. It can also be used to perform numeric operations or comparisons on that data.
        An attack that injects into XPath expressions in order to alter the outcome of the query. Like SQL injection, it can be used to bypass business logic, escalate user privilege, and leak sensitive data. Since applications often use XML to communicate sensitive data across systems and web services, these are the places that are the most vulnerable to XPath injections. Similar to SQL injection, you can prevent XPath injection by using parameterized queries.` },
    { que: "Header Injection",
        ans: `when HTTP response headers are dynamically constructed from untrusted input. Depending on which response header the vulnerability affects, header injection can lead to cross-site scripting, open redirect, and session fixation.
        Ex: if Location header can be controlled by a URL parameter, attackers can cause an open redirect by specifying their malicious site in the parameter. Attackers might even be able to execute malicious scripts on the victim’s browser, or force victims to download malware by sending completely controlled HTTP responses to the victim via header injection. Prevent header injections by avoiding writing user input into response headers, stripping new-line characters from user input (newline characters are used to create new HTTP response headers), and using an allowlist to validate header values.` },
    { que: "Session Injection and Insecure Cookies",
        ans: `Session injection is a type of header injection. If an attacker can manipulate the contents of their session cookie, or steal someone else’s cookies, they can trick the application into thinking that they are someone else. There are three main ways that an attacker can obtain someone else’s session: session hijacking, session tampering, and session spoofing.` },
    { que: "Session hijacking",
        ans: `the attacker stealing someone else session cookie and using it as their own. Attackers often steal session cookies with XSS or MITM (man-in-the-middle) attacks.` },
    { que: "Session tampering",
        ans: `when attackers can change their session cookie to change how the server interprets their identity. This happens when the session state is communicated in the cookie and the cookie is not properly signed or encrypted.` },
    { que: "“Spoof” sessions",
        ans: `Attackers "spoof sessions when session IDs are predictable. Attackers forge valid session cookies and log in as someone else. Preventing these session management pitfalls requires multiple layers of defense."` },
    { que: "Host Header Poisoning",
        ans: `Web servers often host multiple different websites on the same IP address. After an HTTP request arrives at an IP address, the server will forward the request to the host specified in the Host header. Although Host headers are typically set by a user’s browser, it’s still user-provided input and thus should not be trusted.
        If a web application does not validate the Host header before using it to construct addresses, attackers can launch a range of attacks, like XSS, server-side request forgery _(_SSRF), and web cache poisoning attacks via the Host header. For instance, if the application uses the Host header to determine the location of scripts, the attacker could submit a malicious Host header to make the application execute a malicious script:
        String scriptURL = "https://" + properties.getProperty("host") + "/script.js"; ` },
    { que: "Sensitive Data Leaks",
        ans: `when an application fails to properly protect sensitive information, giving users access to information they shouldn’t have available to them. This sensitive information can include technical details that aid an attack, like software version numbers, internal IP addresses, sensitive filenames, and file paths. It could also include source code that allows attackers to conduct a source code review on the application. Sometimes, the application leaks private information of users, such as their bank account numbers, email addresses, and mailing addresses.
        Some common ways that an application can leak sensitive technical details are through descriptive response headers, descriptive error messages with stack traces or database error messages, open directory listings on the system’s file system, and revealing comments in HTML and template files.` },
    { que: "Authentication Bypass",
        ans: `Authentication is proving one’s identity before executing sensitive actions or accessing sensitive data. If authentication is not implemented correctly on an application, attackers can exploit misconfigurations to gain access to functionalities.` },
    { que: "Improper Access Control",
        ans: `Authentication bypass issues are essentially improper access control. Improper access control occurs anytime when access control in an application is improperly implemented and can be bypassed by an attacker. However, access control comprises of more than authentication. While authentication asks a user to prove their identity: “Who are you?”, authorization asks the application “What is this user allowed to do?”. Proper authentication and authorization together ensure that users cannot access functionalities outside of their permissions.
        There are several ways of configuring authorization for users: role-based access control, ownership-based access control, access control lists, and more. ` },
    { que: "Directory Traversal",
        ans: `another type of improper access control. When attackers can view, modify, or execute files they shouldn’t have access to by manipulating file paths in user-input fields. This process involves manipulating file path variables the application uses to reference files by adding the ../ characters or other special characters to the file path. The ../ sequence refers to the parent directory of the current directory in Unix systems, so by adding it to a file path, you can often reach system files outside the web directory.
        Attackers use directory traversals to access sensitive files(configuration files, log files, and source code). To prevent directory traversals, you should validate user input that is inserted into file paths, or avoid direct references to file names and use indirect identifiers` },
    { que: "Arbitrary File Writes",
        ans: `work similarly to directory traversals. If an application writes files to the underlying machine and determines the output file name via user input, attackers might be able to create arbitrary files on any path they want, or overwrite existing system files. Attackers might be able to alter critical system files like password files or log files, or add their own executables into script directories.
        The best way to mitigate this risk is by not creating file names based on any user input, including session information, HTTP input, or anything that the user controls. You should control the file name, path, and extension for every created file. For instance, you can generate a random alphanumeric filename every time the user needs to generate a unique file. You can also strip user input of special characters before creating the file. ` },
    { que: "Denial of Service Attacks",
        ans: `"DoS attacks", disrupts the target machine so that legitimate users cannot access its services. Attackers can launch DoS attacks by exhausting all the server’s resources, crashing processes, or making too many HTTP requests at once.
        Denial of service attacks are hard to defend against. To minimize your risk by making it as difficult as possible for attackers, you can deploy a firewall that offers DoS protection, and prevent logic-based DoS attacks by setting limits on file sizes and disallowing certain file types. ` },
    { que: "Encryption Vulnerabilities",
        ans: `one of the most severe vulnerabilities that can happen in an application. Encryption vulnerabilities refer to when encryption and hashing are not properly implemented. This can lead to widespread data leaks and authentication bypass through session spoofing.
        common mistakes developers make when implementing encryption on a site:
        Using weak algorithms.
        Using the wrong algorithm for the purpose.
        Creating custom algorithms.
        Generating weak random numbers.
        Mistaking encoding for encryption.` },
    { que: "Insecure TLS Configuration and Improper Certificate Validation",
        ans: `make sure that your application in transmitting data properly. A good way of making sure that you are communicating over the Internet securely is to use HTTPS with a modern version of transport layer security (TLS) and a secure cipher suite.
        During this process, you need to ensure that you are communicating with a trusted machine, and not a malicious third-party. TLS uses digital certificates as the basis of its public key encryption, and you need to validate these certificates before establishing the connection with the third-party. You should verify that the server you are trying to connect to has a certificate that is issued by a trusted certificate authority (CA) and that none of the certificates in the certificate chain are expired.` },
    { que: "Mass Assignment",
        ans: `the practice of assigning values to multiple variables or object properties all at once. Mass assignment vulnerabilities happen when the application automatically assigns user input to multiple program variables or objects. This is a feature in many application frameworks designed to simplify application development.
        However, this feature sometimes allows attackers to overwrite, modify, or create new program variables or object properties at will. This can lead to authentication bypass, and manipulation of program logic. To prevent mass assignments, you can disable the mass assignment feature with the framework you are using, or use a whitelist to only allow assignment on certain properties or variables.` },
    { que: "Open Redirects",
        ans: `Websites often need to automatically redirect their users. This happens when unauthenticated users try to access a page that requires logging in. The website will usually redirect those users to thelogin page, and then return them to their original location after they are authenticated.
        During an open-redirect attack, an attacker tricks the user into visiting an external site by providing them with a URL from the legitimate site that redirects somewhere else. This can lead users to believe that they are still on the original site, and help scammers build a more believable phishing campaign.
        To prevent open redirects, you need to make sure the application doesn’t redirect users to malicious locations. For instance, you can disallow offsite redirects completely by validating redirect URLs. There are many other ways of preventing open redirects, like checking the referrer of requests, or using page indexes for redirects. But because it’s difficult to validate URLs, open redirects remain a prevalent issue in modern web applications.` },
    { que: "Cross-Site Request Forgery(CSRF)",
        ans: ` client-side technique used to attack other users of a web application. Using CSRF, attackers can send HTTP requests that pretend to come from the victim, carrying out unwanted actions on a victim’s behalf. For example, an attacker could change your password or transfer money from your bank account without your permission.
        Unlike open redirects, a surefire way of preventing CSRF: using a combination of CSRF tokens and SameSite cookies, and avoid using GET requests for state-changing actions.` },
    { que: "Server-Side Request Forgery(SSRF)",
        ans: `a vulnerability that happens when an attacker is able to send requests on behalf of a server. It allows attackers to “forge” the request signatures of the vulnerable server, therefore assuming a privileged position on a network, bypassing firewall controls, and gaining access to internal services.
        Depending on the permissions given to the vulnerable server, an attacker might be able to read sensitive files, make internal API calls, and access internal services like hidden admin panels. The easiest way to prevent SSRF vulnerabilities is to never make outbound requests based on user input. But if you do need to make outbound requests based on user input, you’ll need to validate those addresses before initiating the request.` },
    { que: "Trust Boundary Violations",
        ans: `where untrusted user input enters a controlled environment. Ex: an HTTP request is considered untrusted input until it has been validated by the server.
        There should be a clear distinction between how you store, transport, and process trusted and untrusted input. Trust boundary violations happen when this distinction is not respected, and trusted and untrusted data are confused with each other. For instance, if trusted and untrusted data are stored in the same data structure or database, the application will start confusing the two. In this case, untrusted data might be mistakenly seen as validated.
        A good way to prevent trust boundary violation is to never write untrusted input into session stores until it is verified. ` },
    { que: "📁 Python Security Considerations",
        ans: `https://docs.python.org/3/library/security_warnings.html` },
    { que: "base64 in RFC 4648",
        ans: `` },
    { que: "hashlib - Secure hashes and message digests",
        ans: `` },
    { que: "hashlib: all constructors take 'usedforsecurity' keyword-only",
        ans: `` },
    { que: "http.server",
        ans: `` },
    { que: "logging: Logging configuration uses eval()",
        ans: `` },
    { que: "multiprocessing: connection.recv() uses pickle",
        ans: `` },
    { que: "pickle: Restricting globals in pickle",
        ans: `` },
    { que: "random: use secrets",
        ans: `` },
    { que: "shelve: based on pickle and unsuitable for dealing w untrusted sources",
        ans: `` },
    { que: "ssl/tls security considerations",
        ans: `` },
    { que: "subprocess security considerations",
        ans: `` },
    { que: "tempfile: mktemp deprecated to vulnerability to race conditions",
        ans: `` },
    { que: "xml security",
        ans: `` },
    { que: "zipfile: cause disk volume exhaustion",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
];