const flashcards = [
    { que: "Security",
        ans: `investment that represents either ownership/debt stake. Investor becomes part owner in a corporation by buying shares of the company's stock. Debt security is acquired by buying issuer's (corporation/goverment) bonds. Debt investment is a loan to the issuer in exchange for interest income and the promise to repay the loan at future maturity date.` },
    { que: "Common Stock",
        ans: `equity(ownership) in corporation. A company issues stock to raise capital, and investors who buy the stock are buying a share of ownership in the company. The exam will deal with stock that has been issues to the public.` },
    { que: "Board of directors",
        ans: `individuals that oversee company business. They are selected to make decisions on behalf of shareholders.` },
    { que: "Preferred Stock",
        ans: `represents equity(ownership) in corporation but doesn't have same voting rights or appreciation potential as common stock. Preferred stock pays fixed dividend(quarterly), and has "priority claims" over common stock.
        Common stockholders cannot receive dividend until preferred shareholders have been paid theirs, and if company goes bankrupt, preferred stockholders have prior claim of remaining assets.
        Preferred Stock is an equity security because it represents a class of ownership in the issuing corporation. It shares characteristics with debt security.` },
    { que: "Capital Appreciation",
        ans: `an increase in the market price of securities.` },
    { que: "Stock Dividends",
        ans: `Issuers pay "stock dividends", in additional shares of common stock in the issuing company."` },
    { que: "Property Dividends",
        ans: `Issuers pay "property dividends", shares in a subsidiary company, or company products.` },
    { que: "Unrealized Gain",
        ans: `stock that appreciates that is not sold.` },
    { que: "Realized Gain",
        ans: `the price increase when the stock is sold. Capital gains are not taxed until they are realized.` },
    { que: "Stock split",
        ans: `accounting process whereby the corporation exchanges new shares for old ones while changing the number of shares outstanding in the marketplace. ex: 2-for-1 stock split; the owner now owns twice as many shares worth half as much.` },
    { que: "preemptive right",
        ans: `Common stockholders, not Preferred stockholders, have preemptive right to maintain their proportionate share of ownership in the corporation.` },
    { que: "Limited Liability",
        ans: `in event of corporation bankruptcy, when corporate assets are not adequate to meet corporate obligations, stockholder's personal assets are not at risk. Cannot be forced to sell personal assets to pay debts of the business.` },
    { que: "Liquidity",
        ans: `Stocks are freely transferrable, meaning stakeholders do not need permission of the issuer to sell their stock in the open market.` },
    { que: "Why include common stock in client's portfolio?",
        ans: `Potential capital appreciation.
        Income from dividends.
        Hedge against inflation.` },
    { que: "Market Risk",
        ans: `chance a stock will decline in price. Stock's price fluctuates daily as perceptions of company's business prospects change and influence the actions of buyers/sellers.` },
    { que: "Business Risk",
        ans: `possibility of a decline in the company's earnings. Could lead to reduction or elimination of dividends.` },
    { que: "Low Priority at Dissolution",
        ans: `When company enters bankruptcy, holders of bonds and preferred stock have priority over common stockholders. Company's debt and preferred shares are considered "senior securities". Common stockholders have "residual rights" to corporate assets upon dissolution.` },
    { que: "Straight(Noncumulative) Preferred Stock",
        ans: `has no special features beyond the stated dividend payment. Missed dividends are not paid to the stockholder.` },
    { que: "Cumulative Preferred Stock",
        ans: `accrues payments due its shareholders in the event dividends are reduced or suspended. Dividends due cumulative preferred stock accumulate on the company's books until the corporation's board of directors decides to pay them. When the company resumes dividend payments, cumulative preferred stockholders receive current dividends plus the total accumulated dividends--dividends "in arrears"--before any dividends may be distributed to common stockholders.
        Ex: Common stock paid dividends $1, preferred dividend paid $2. Company had financial difficulties and stopped paying dividends after 2016. After resolving difficulties in 2021, company paid cumulative preferred stockholders dividend of $8.
        This feature found in cumulative preferred stock, an investor seeking steady income finds this most suitable of different types of preferred stock.` },
    { que: "Callable(Redeemable) Preferred Stock",
        ans: `a compnay can buy back from investors at stated price after specified date. Right to call the stock allows company to replace high fixed dividend obligation with a lower one when the cost of money has gone down. (Similar to refinancing a mortgage).
        When corporation calls preferred stock, dividend payments cease. Corporation pays premium exceeding stock's value ($103 for $100 par value stock).
        Issuing the call create problems for your client who purchased callable preferred shares issued at a time when market conditions dictated high dividend.
        If the cost of new money comes down, company will call preferrred and investor will have to reinvest proceeds at lower rate. Ex: of reinvestment risk.` },
    { que: "Convertible Preferred",
        ans: `preferred stock is "convertible" if owner can exchange shares for fixed number of shares of common stock of the issuing corporation.
        Because the value of convertible preferred is linked to value of common stock, the convertible's preferred price tends to fluctuate in line with common stock.
        Convertible preferred is issued with lower dividend rate than nonconvertible preferred of the same quality becuase the investor have the opportunity to convert common shares and enjoy greater capital gain potential.` },
    { que: "Adjustable-Rate Preferred Stock",
        ans: `issued with adjustable(floating) dividend rates. Dividends are tied to rates of interest rate benchmarks, ex: Treasury bills / money market rates, which can adjust monthly.
        For investors looking for fixed income through preferred stocks, adjustable rate would be least appropirate because dividend fluctuates.
        ` },
    { que: "Preferred stock type can be...",
        ans: `cumulative and callable,
        callable and convertible, 
        or any combination. 
        If not listed, it's straight preferred.` },
    { que: "Primary objective by investing in preferred stock is...",
        ans: `income, when analyzing specific preferred stock, most important determination should be the ability of the company to meet its dividend payments.` },
    { que: "Benefits/Risks of Owning Preferred Stock - Why include in client's portfolio:",
        ans: `Fixed income from dividends.
        Prior claim ahead of common stock.
        Convertible preferred sacrifices income in exchange for potential appreciation.` },
    { que: "Benefits/Risks of Owning Preferred Stock - Client incurs following risks:",
        ans: `Market risk--in economic downturn, fear of ability to maintain dividend will cause price to drop.
        Possible loss of purchasing power.
        Interest rate(money rate) risk.
        Business difficulties leading to possible reduction or elimination of the dividend and even bankruptcy leading to loss of principal.` },
    { que: "Preferred stock regarded as...",
        ans: `fixed-income investment, unlike debt securities, usually has no preset date which it matures and no scheduled redemption date. Preferred stock is a "perpetual security."` },
    { que: "Nonqualified Stock Options(NSOs/NQSOs)",
        ans: `more common than incentive stock options(ISOs).NSOs are treated as form of compensation. When exercising NSOs, the difference between current market price at time of exercise and strike price, referred as "bargain element", is reported as wages on tax returns of employer & employee. Instead of capital gains, the employee is taxed as ordinary income on that bargain element while the company receives tax deduction as salary expense for that same amount.
        Ex: employee exercises NSO at $53/share when current fair value is $66.50. "Bargain element" is $14.50(the difference of exercise price and fair value). If exercise for $100 shares($1450 ordinary income), the corporation treats that as deductible salary expense.
        Because the spread between market price and strike price is considered salary, it's subject to payroll taxes as well as income tax.` },
    { que: "Incentive Stock Options(ISOs)",
        ans: `No tax consequences to employer with ISO, but can be advantageous to the employee than NSOs. For employees: as long as stock purchased held at least 2 years after date of grant and 1 year after date of exercise, profits are long-term capital gain, another stipulation is max 10 year limit for exercise.
        When ISO is exercised, the difference between market value at time of purchase and strike price is preference item is used in calculating alternative minimum tax(AMT)` },
    { que: "Incentive ISO summary",
        ans: `No income recognized when option is granted.
        No tax due when option is exercised.
        Tax is due when stock is sold.
        Gain is capital(long term) when held at least one year and sold at least two years after grant, otherwise, ordinary income.
        Difference between option price and fair market value(FMV) on date of exercise is add back for AMT purposes.` },
    { que: "Restricted Securities",
        ans: `retail investors cannot sell until having held them for certain period of time, generally 6 months.` },
    { que: "Control Stock",
        ans: `stock is held by control person.
        Always has volume limits.` },
    { que: "Control Person",
        ans: `a corporate director, officer, large stockholder, or immediate family of any preceding residing in same home.
        Generally referred as affiliates becuase of their unique status within issuer.` },
    { que: "Form 144",
        ans: `mechanism for reporting the sale of control stock / restricted stock, found in SEC Rule 144 of Securities Act of 1933.` },
    { que: "American Depositary Receipts(ADRs)",
        ans: `facilitate trading of foreign stocks in US markets because everything is done in English, US dollars. ADRs are bought/sold/traded in $USD, dividends are paid in $USD.
        ADR is negotiable security that represent receipt of stock in non-US corporation. ADRs are bought/sold in US securities markets like domestic stock.` },
    { que: "Rights of ADR Owners",
        ans: `Most of the rights that common stockholders normally hold, such as the right to receive dividiends, also apply to ADR owners. In some, but not all, cases, there are also voting rights.
        For exam purposes: ADRs never have preemptive rights` },
    { que: "Currency Risk",
        ans: `in addition to risks of ADRs, currency risk, is the possibility that an investment denominated in one currency(ex: Mexican peso) could decline if the value of that currency declines in its exchange rate with the $USD. Because ADRs represent shares of stock in companies located in foreign countries, currency exchange rates are an important consideration.` },
    { que: "ADR - Take Note!",
        ans: `Banks collect dividend payments, convert them into US funds for US owners, and withhold any required foreign tax payments.
        Owners of ADRs can claim US tax credit for these withholdings.` },
    { que: "!ADR - Test Topic Alert!",
        ans: `Exam will want you to know ADRs are issued by domestic branches of US banks, even though they are traded in $USD, they still bear currency risk.` },
    { que: "Investing in Foreign Markets",
        ans: `foreign securities offer investors the potential for substantial gains, they bear a variety of risks that are not present with domestic investments. Two broad market classifications of foreign markets(Emerging/Developed)` },
    { que: "Emerging Markets",
        ans: `are markets in less-developed countries. Associated with:
        Low levels of income, measured by country's "Gross Domestic Product(GDP).
        Low levels of equity capitalization.
        Questionable market liquidity.
        Potential restrictions on currency conversion.
        High volatility.
        Prospects for economic growth and devleopment.
        Stabilizing political/social institutions.
        High taxes and commission costs for foreign investors.
        Restrictions on foreign ownership and on foreign currency conversion.
        Lower regulatory standards resulting in a lack of transparency."` },
    { que: "Frontier Market",
        ans: `Frontier markets are to emerging markets as emerging markets are to developed ones. Risks are extremely high.` },
    { que: "Developed Markets",
        ans: `associated with countries that have highly developed economies with stable political/social institutions. Characterized by:
        Large levels of equity capitalization.
        Low commission rates.
        Few currency conversion restrictions.
        Highly liquid markets with many brokerage institutions and market makers.
        Many large capitalization securities.
        Well-defined regulatory schemes leading to transparency similar to that enjoyed by those investing in US securities.
        Why add foreign securities to client's portfolio:
        Expanded potential investment universe leading to greater diversification.
        Foreign securities sometimes outperform domestic ones.
        Foreign securities are usually not highly correlated with domestic ones, resulting overall risk of portfolio reduced.` },
    { que: "Risks of Investing in Foreign Markets",
        ans: `` },
    { que: "Country Risk",
        ans: `` },
    { que: "Exchange  Controls",
        ans: `restricted from immediate resell, must be held for certain period, generally 6 months.` },
    { que: "Control Stock",
        ans: `held by "control person" (corporate director, officer, large stockholder, immediate family of any of preceding residing in same home). Generally referred to as affiliates due to unique status within issuer.` },
    { que: "Reporting Restricted/Control Stock",
        ans: `found in SEC Rule 144 of Securities Act of 1933. To sell stock, bmust file Form 144.` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "Foreign Countries - Withholding, Fees, Taxes",
        ans: `foreign countries may withhold portion of dividends and capital gains for taxes. Some impose heavy fees and taxes on securities that investor must bear in addition to generally higher brokerage commissions.` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
    { que: "",
        ans: `` },
];